---
apt_dir: /etc/apt
apt_users: _apt
apt_conf_dir: '{{ apt_dir }}/apt.conf.d'
apt_sources_dir: '{{ apt_dir }}/sources.list.d'
apt_preferences_dir: '{{ apt_dir }}/preferences.d'
apt_trusted_gpg_dir: '{{ apt_dir }}/trusted.gpg.d'
