---
dependencies:
  - role: apt
    when: ansible_os_family == "Debian"
    apt:
      keys_:
        - name: xpra.gpg
          src: apt/keys/xpra.gpg
      sources:
        purge: yes
        includes:
          - name: xpra
            entries:
              - type: deb
                uri: "https://xpra.org/dists"
                suite: "bookworm"
                components:
                  - main
                options:
                  - signed-by=/etc/apt/trusted.gpg.d/xpra.gpg
      preferences:
        purge: yes
        includes:
          - name: xpra
            entries:
            - packages: xpra xpra-x11 xpra-server xpra-client xpra-client-gtk3 xpra-codecs xpra-common
              version: "5*"
              origin: xpra.org
              priority: 999
            - packages: "*"
              origin: xpra.org
              priority: 1
  - role: packages
    when: ansible_os_family == "Debian"
    packages:
      update_cache: true
      upgrade: false
      clean: false
      install:
        - xpra=5.0.9-r0-1
        - xpra-client=5.0.9-r0-1
        - xpra-client-gtk3=5.0.9-r0-1
        - xpra-server=5.0.9-r0-1
        - xpra-codecs=5.0.9-r0-1
        - xpra-common=5.0.9-r0-1
        - xpra-x11=5.0.9-r0-1
        - python3-rencode # to work with debian 12 native package
        - dbus-x11
     
